// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"webhooklenna/config"
	"webhooklenna/controllers"
	"webhooklenna/controllers/webhookController/webchatController"
	"webhooklenna/repositories/webhookRepository/webchatRepository"
	"webhooklenna/services/webhookService/webchatService"
)

// Injectors from injector.go:

func InitializeController() *controllers.AllController {
	db := config.Postgres()
	webhookWebchatRepositoryImpl := webchatrepository.NewWebhookWebchatRepository(db)
	webhookWebchatServiceImpl := webchatservice.NewWebhookWebchatService(webhookWebchatRepositoryImpl)
	webhookWebchatControllerImpl := webchatcontroller.NewWebhookWebchatController(webhookWebchatServiceImpl)
	allController := controllers.NewAllController(webhookWebchatControllerImpl)
	return allController
}

// injector.go:

var WebhookWebchatSet = wire.NewSet(config.Postgres, webchatrepository.NewWebhookWebchatRepository, wire.Bind(new(webchatrepository.WebhookWebchatRepository), new(*webchatrepository.WebhookWebchatRepositoryImpl)), webchatservice.NewWebhookWebchatService, wire.Bind(new(webchatservice.WebhookWebchatService), new(*webchatservice.WebhookWebchatServiceImpl)), webchatcontroller.NewWebhookWebchatController, wire.Bind(new(webchatcontroller.WebhookWebchatController), new(*webchatcontroller.WebhookWebchatControllerImpl)), controllers.NewAllController)
